-- Approvisionnement: header document + received lines.
-- `supplier_name` is a free text snapshot (no supplier table yet in this
-- version), the reference is generated by the service, the total and the line
-- totals are always recomputed from the lines before insertion.
CREATE TABLE `supplies` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`reference` text NOT NULL,
	`supplier_name` text,
	`date` integer NOT NULL,
	`total_amount` integer NOT NULL,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	CONSTRAINT "supplies_total_amount_check" CHECK("supplies"."total_amount" >= 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX `supplies_reference_unique` ON `supplies` (`reference`);--> statement-breakpoint
CREATE INDEX `supplies_date_idx` ON `supplies` (`date`);--> statement-breakpoint
CREATE TABLE `supply_items` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`supply_id` integer NOT NULL,
	`product_id` integer NOT NULL,
	`form` text NOT NULL,
	`quantity` integer NOT NULL,
	`purchase_unit_price` integer NOT NULL,
	`line_total` integer NOT NULL,
	FOREIGN KEY (`supply_id`) REFERENCES `supplies`(`id`) ON UPDATE cascade ON DELETE cascade,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE cascade ON DELETE restrict,
	CONSTRAINT "supply_items_quantity_check" CHECK("supply_items"."quantity" > 0),
	CONSTRAINT "supply_items_purchase_unit_price_check" CHECK("supply_items"."purchase_unit_price" >= 0),
	CONSTRAINT "supply_items_line_total_check" CHECK("supply_items"."line_total" >= 0)
);
--> statement-breakpoint
CREATE INDEX `supply_items_supply_id_idx` ON `supply_items` (`supply_id`);--> statement-breakpoint
CREATE INDEX `supply_items_product_id_idx` ON `supply_items` (`product_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `supply_items_supply_product_form_unique` ON `supply_items` (`supply_id`,`product_id`,`form`);--> statement-breakpoint
-- APPROVISIONNEMENT joins STOCK_INITIAL and AJUSTEMENT as a movement type.
-- SQLite cannot ALTER a CHECK constraint, so the table is rebuilt the official
-- way: every existing row is copied (ids and dates included), the previous
-- constraints are recreated as they were and a supply is forced to be an IN
-- movement. No stock history is lost, never rewritten.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_stock_movements` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`product_id` integer NOT NULL,
	`form` text NOT NULL,
	`movement_type` text NOT NULL,
	`direction` text NOT NULL,
	`quantity` integer NOT NULL,
	`reason` text,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE cascade ON DELETE restrict,
	CONSTRAINT "stock_movements_quantity_check" CHECK("__new_stock_movements"."quantity" > 0),
	CONSTRAINT "stock_movements_direction_check" CHECK("__new_stock_movements"."direction" in ('IN', 'OUT')),
	CONSTRAINT "stock_movements_type_check" CHECK("__new_stock_movements"."movement_type" in ('STOCK_INITIAL', 'AJUSTEMENT', 'APPROVISIONNEMENT')),
	CONSTRAINT "stock_movements_initial_direction_check" CHECK("__new_stock_movements"."movement_type" <> 'STOCK_INITIAL' or "__new_stock_movements"."direction" = 'IN'),
	CONSTRAINT "stock_movements_supply_direction_check" CHECK("__new_stock_movements"."movement_type" <> 'APPROVISIONNEMENT' or "__new_stock_movements"."direction" = 'IN'),
	CONSTRAINT "stock_movements_reason_check" CHECK("__new_stock_movements"."movement_type" <> 'AJUSTEMENT' or ("__new_stock_movements"."reason" is not null and length(trim("__new_stock_movements"."reason")) > 0))
);
--> statement-breakpoint
INSERT INTO `__new_stock_movements`("id", "product_id", "form", "movement_type", "direction", "quantity", "reason", "created_at") SELECT "id", "product_id", "form", "movement_type", "direction", "quantity", "reason", "created_at" FROM `stock_movements`;--> statement-breakpoint
DROP TABLE `stock_movements`;--> statement-breakpoint
ALTER TABLE `__new_stock_movements` RENAME TO `stock_movements`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE INDEX `stock_movements_product_id_idx` ON `stock_movements` (`product_id`);--> statement-breakpoint
CREATE INDEX `stock_movements_product_form_idx` ON `stock_movements` (`product_id`,`form`);--> statement-breakpoint
CREATE UNIQUE INDEX `stock_movements_initial_unique` ON `stock_movements` (`product_id`,`form`) WHERE "stock_movements"."movement_type" = 'STOCK_INITIAL';