-- Transformation: header document of a conversion between the two forms of a
-- transformable product. The reference is generated by the service, the
-- destination form is always the other form of the product and the destination
-- quantity is always recomputed from the conversion of the product.
CREATE TABLE `transformations` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`reference` text NOT NULL,
	`product_id` integer NOT NULL,
	`source_form` text NOT NULL,
	`source_quantity` integer NOT NULL,
	`destination_form` text NOT NULL,
	`destination_quantity` integer NOT NULL,
	`date` integer NOT NULL,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE cascade ON DELETE restrict,
	CONSTRAINT "transformations_source_quantity_check" CHECK("transformations"."source_quantity" > 0),
	CONSTRAINT "transformations_destination_quantity_check" CHECK("transformations"."destination_quantity" > 0),
	CONSTRAINT "transformations_forms_check" CHECK("transformations"."source_form" <> "transformations"."destination_form")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `transformations_reference_unique` ON `transformations` (`reference`);--> statement-breakpoint
CREATE INDEX `transformations_product_id_idx` ON `transformations` (`product_id`);--> statement-breakpoint
CREATE INDEX `transformations_date_idx` ON `transformations` (`date`);--> statement-breakpoint
-- TRANSFORMATION joins STOCK_INITIAL, AJUSTEMENT and APPROVISIONNEMENT as a
-- movement type. It is the only type allowed in both directions (OUT on the
-- source form, IN on the destination form) and it never carries a reason.
-- SQLite cannot ALTER a CHECK constraint, so the table is rebuilt the official
-- way: every existing row is copied (ids and dates included), the previous
-- constraints are recreated as they were and the movement history is never lost,
-- never rewritten.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_stock_movements` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`product_id` integer NOT NULL,
	`form` text NOT NULL,
	`movement_type` text NOT NULL,
	`direction` text NOT NULL,
	`quantity` integer NOT NULL,
	`reason` text,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE cascade ON DELETE restrict,
	CONSTRAINT "stock_movements_quantity_check" CHECK("__new_stock_movements"."quantity" > 0),
	CONSTRAINT "stock_movements_direction_check" CHECK("__new_stock_movements"."direction" in ('IN', 'OUT')),
	CONSTRAINT "stock_movements_type_check" CHECK("__new_stock_movements"."movement_type" in ('STOCK_INITIAL', 'AJUSTEMENT', 'APPROVISIONNEMENT', 'TRANSFORMATION')),
	CONSTRAINT "stock_movements_initial_direction_check" CHECK("__new_stock_movements"."movement_type" <> 'STOCK_INITIAL' or "__new_stock_movements"."direction" = 'IN'),
	CONSTRAINT "stock_movements_supply_direction_check" CHECK("__new_stock_movements"."movement_type" <> 'APPROVISIONNEMENT' or "__new_stock_movements"."direction" = 'IN'),
	CONSTRAINT "stock_movements_reason_check" CHECK("__new_stock_movements"."movement_type" <> 'AJUSTEMENT' or ("__new_stock_movements"."reason" is not null and length(trim("__new_stock_movements"."reason")) > 0)),
	CONSTRAINT "stock_movements_transformation_reason_check" CHECK("__new_stock_movements"."movement_type" <> 'TRANSFORMATION' or "__new_stock_movements"."reason" is null)
);
--> statement-breakpoint
INSERT INTO `__new_stock_movements`("id", "product_id", "form", "movement_type", "direction", "quantity", "reason", "created_at") SELECT "id", "product_id", "form", "movement_type", "direction", "quantity", "reason", "created_at" FROM `stock_movements`;--> statement-breakpoint
DROP TABLE `stock_movements`;--> statement-breakpoint
ALTER TABLE `__new_stock_movements` RENAME TO `stock_movements`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE INDEX `stock_movements_product_id_idx` ON `stock_movements` (`product_id`);--> statement-breakpoint
CREATE INDEX `stock_movements_product_form_idx` ON `stock_movements` (`product_id`,`form`);--> statement-breakpoint
CREATE UNIQUE INDEX `stock_movements_initial_unique` ON `stock_movements` (`product_id`,`form`) WHERE "stock_movements"."movement_type" = 'STOCK_INITIAL';