-- Facturation : header document of a sale (a facture).
-- The reference is generated by the service (VTE-000001), the client is always
-- present (the system client "CLIENT COMPTANT" is used when none is selected),
-- the status is VALIDEE at creation and the total is recomputed from the lines.
CREATE TABLE `sales` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`reference` text NOT NULL,
	`client_id` integer NOT NULL,
	`sale_date` integer NOT NULL,
	`status` text NOT NULL,
	`total_amount` integer NOT NULL,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE cascade ON DELETE restrict,
	CONSTRAINT "sales_status_check" CHECK("sales"."status" in ('VALIDEE', 'ANNULEE')),
	CONSTRAINT "sales_total_amount_check" CHECK("sales"."total_amount" >= 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX `sales_reference_unique` ON `sales` (`reference`);
--> statement-breakpoint
CREATE INDEX `sales_client_id_idx` ON `sales` (`client_id`);
--> statement-breakpoint
CREATE INDEX `sales_sale_date_idx` ON `sales` (`sale_date`);
--> statement-breakpoint
CREATE INDEX `sales_status_idx` ON `sales` (`status`);
--> statement-breakpoint
-- One line of a sale. `form` is the form really sold (a transformable product can
-- be sold in either of its two forms, with no automatic conversion) and
-- `unit_price` is the real price applied on this document: the price of the
-- product can change later without rewriting the history.
CREATE TABLE `sale_items` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`sale_id` integer NOT NULL,
	`product_id` integer NOT NULL,
	`form` text NOT NULL,
	`quantity` integer NOT NULL,
	`unit_price` integer NOT NULL,
	`line_total` integer NOT NULL,
	FOREIGN KEY (`sale_id`) REFERENCES `sales`(`id`) ON UPDATE cascade ON DELETE cascade,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE cascade ON DELETE restrict,
	CONSTRAINT "sale_items_quantity_check" CHECK("sale_items"."quantity" > 0),
	CONSTRAINT "sale_items_unit_price_check" CHECK("sale_items"."unit_price" >= 0),
	CONSTRAINT "sale_items_line_total_check" CHECK("sale_items"."line_total" >= 0)
);
--> statement-breakpoint
CREATE INDEX `sale_items_sale_id_idx` ON `sale_items` (`sale_id`);
--> statement-breakpoint
CREATE INDEX `sale_items_product_id_idx` ON `sale_items` (`product_id`);
--> statement-breakpoint
CREATE UNIQUE INDEX `sale_items_sale_product_form_unique` ON `sale_items` (`sale_id`,`product_id`,`form`);
--> statement-breakpoint
-- A payment of a sale. There is no payment method in this version: only the
-- amount and the date are recorded. The payment status is always recomputed
-- from the sum of the payments against the total of the sale.
CREATE TABLE `payments` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`sale_id` integer NOT NULL,
	`amount` integer NOT NULL,
	`payment_date` integer NOT NULL,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	FOREIGN KEY (`sale_id`) REFERENCES `sales`(`id`) ON UPDATE cascade ON DELETE cascade,
	CONSTRAINT "payments_amount_check" CHECK("payments"."amount" > 0)
);
--> statement-breakpoint
CREATE INDEX `payments_sale_id_idx` ON `payments` (`sale_id`);
--> statement-breakpoint
CREATE INDEX `payments_payment_date_idx` ON `payments` (`payment_date`);
--> statement-breakpoint
-- SALE joins STOCK_INITIAL, AJUSTEMENT, APPROVISIONNEMENT and TRANSFORMATION as a
-- movement type. It is the only new type added by the facturation module and it
-- is always an OUT movement (a facture removes stock). It always carries the
-- reference of the facture it comes from as its reason ("Facture VTE-000001"),
-- so the stock history always points back to the document that moved it.
-- The movements that give a stock back (modification of an unpaid facture,
-- cancellation) are AJUSTEMENT entries naming the same facture: SALE only
-- removes, so its direction can never be IN.
-- SQLite cannot ALTER a CHECK constraint, so the table is rebuilt the official
-- way: every existing row is copied (ids and dates included), the previous
-- constraints are recreated as they were and the movement history is never lost,
-- never rewritten.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_stock_movements` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`product_id` integer NOT NULL,
	`form` text NOT NULL,
	`movement_type` text NOT NULL,
	`direction` text NOT NULL,
	`quantity` integer NOT NULL,
	`reason` text,
	`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON UPDATE cascade ON DELETE restrict,
	CONSTRAINT "stock_movements_quantity_check" CHECK("__new_stock_movements"."quantity" > 0),
	CONSTRAINT "stock_movements_direction_check" CHECK("__new_stock_movements"."direction" in ('IN', 'OUT')),
	CONSTRAINT "stock_movements_type_check" CHECK("__new_stock_movements"."movement_type" in ('STOCK_INITIAL', 'AJUSTEMENT', 'APPROVISIONNEMENT', 'TRANSFORMATION', 'SALE')),
	CONSTRAINT "stock_movements_initial_direction_check" CHECK("__new_stock_movements"."movement_type" <> 'STOCK_INITIAL' or "__new_stock_movements"."direction" = 'IN'),
	CONSTRAINT "stock_movements_supply_direction_check" CHECK("__new_stock_movements"."movement_type" <> 'APPROVISIONNEMENT' or "__new_stock_movements"."direction" = 'IN'),
	CONSTRAINT "stock_movements_reason_check" CHECK("__new_stock_movements"."movement_type" <> 'AJUSTEMENT' or ("__new_stock_movements"."reason" is not null and length(trim("__new_stock_movements"."reason")) > 0)),
	CONSTRAINT "stock_movements_transformation_reason_check" CHECK("__new_stock_movements"."movement_type" <> 'TRANSFORMATION' or "__new_stock_movements"."reason" is null),
	CONSTRAINT "stock_movements_sale_direction_check" CHECK("__new_stock_movements"."movement_type" <> 'SALE' or "__new_stock_movements"."direction" = 'OUT'),
	CONSTRAINT "stock_movements_sale_reason_check" CHECK("__new_stock_movements"."movement_type" <> 'SALE' or ("__new_stock_movements"."reason" is not null and length(trim("__new_stock_movements"."reason")) > 0))
);
--> statement-breakpoint
INSERT INTO `__new_stock_movements`("id", "product_id", "form", "movement_type", "direction", "quantity", "reason", "created_at") SELECT "id", "product_id", "form", "movement_type", "direction", "quantity", "reason", "created_at" FROM `stock_movements`;--> statement-breakpoint
DROP TABLE `stock_movements`;--> statement-breakpoint
ALTER TABLE `__new_stock_movements` RENAME TO `stock_movements`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE INDEX `stock_movements_product_id_idx` ON `stock_movements` (`product_id`);--> statement-breakpoint
CREATE INDEX `stock_movements_product_form_idx` ON `stock_movements` (`product_id`,`form`);--> statement-breakpoint
CREATE UNIQUE INDEX `stock_movements_initial_unique` ON `stock_movements` (`product_id`,`form`) WHERE "stock_movements"."movement_type" = 'STOCK_INITIAL';